### ISSUE TITLE
The example doesn't build out of the box

### ISSUE THREAD

**Issue by ghost** [lthibault/quic-mangos#6]
What's wrong:
When trying to build, I get:

net.go:241:16: too many arguments in call to r.Session.Close

How to reproduce:
- Must have a clean GOPATH
- Copy and paste the example code from github into main.go
- Use dep or vgo to automatically resolve vendor support
- Rung build or test

Coplaint is that Session.Close(nil) is not the correct signature.

**Comment by lthibault** [comment]
Thanks for reporting this!
It looks like the upstream `github.com/lucas-clemente/quic-go` changed the `Session` interface.  It used to be that `quic.Session` had the function `Close(err error) error`, but this has been supplanted with 

```go
type Session interface {
    ...
    Close() error
    CloseWithError(error) error
}
```
I've made the necessary changes; everything should now work as expected.

Out of pure curiosity, what are you using this library for?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/1952419/45131906-fc221600-b15c-11e8-9430-9a6b3dd225f0.png)

So, even with the upstream changes, I still get build errors.

To answer you question, I was evaluating this for as potential production quality implementation of QUIC.

**Comment by lthibault** [comment]
Hi Karim,
Fear not -- we'll get this working for you ;)
 
1. Can you show me your code?
1. Why/what are you vendoring?
1. Are you able to run the example?  If not, can you try running it without the vendoring just to make sure everything works as expected at that level?

> I was evaluating this for as potential production quality implementation of QUIC.

May I ask what the use-case for such an implementation be?  I just like to have an idea of what users are doing -- it help make good decisions.

**Comment by ghost** [comment]
Sorry for the slow reply. We've already moved on. The use case intent was to provide low latency messaging between micro-services intended as data resolution points for a GraphQL proxy.

My code is very very simple. 'go get' the package as described in the markdown... go into the example directory and run go build. I've not added any code on top of it.

Personally hope you get this working, it seems very interesting and promising.

here is the attempt from this morning:
```$ go build example/pair/main.go 
# command-line-arguments
example/pair/main.go:29:35: cannot use quic.NewTransport() (type "github.com/nanomsg/mangos".Transport) as type "nanomsg.org/go-mangos".Transport in argument to s0.AddTransport:
	"github.com/nanomsg/mangos".Transport does not implement "nanomsg.org/go-mangos".Transport (wrong type for NewDialer method)
		have NewDialer(string, "github.com/nanomsg/mangos".Socket) ("github.com/nanomsg/mangos".PipeDialer, error)
		want NewDialer(string, "nanomsg.org/go-mangos".Socket) ("nanomsg.org/go-mangos".PipeDialer, error)
example/pair/main.go:30:35: cannot use quic.NewTransport() (type "github.com/nanomsg/mangos".Transport) as type "nanomsg.org/go-mangos".Transport in argument to s1.AddTransport:
	"github.com/nanomsg/mangos".Transport does not implement "nanomsg.org/go-mangos".Transport (wrong type for NewDialer method)
		have NewDialer(string, "github.com/nanomsg/mangos".Socket) ("github.com/nanomsg/mangos".PipeDialer, error)
		want NewDialer(string, "nanomsg.org/go-mangos".Socket) ("nanomsg.org/go-mangos".PipeDialer, error)```
